name: Frontend CI

on:
  push:
    branches:
      - staging   # run only when pushing to the 'staging' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - run: npm ci
      - run: npm run ci       # lint + test + build
      - run: npm run deploy:staging
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
